=== griff182uk/teamconfig/teams/schema/team.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "description": "A Team in an organisation",
    "required": [
        "overview",
        "members",
        "communications",
        "products"
    ],
    "properties": {
        "overview": {
            "$ref": "#/$defs/overview"
        },
        "communications": {
            "type": "array",
            "description": "The communication methods of the team.",
            "items": {
                "$ref": "#/$defs/communication"
            },
            "uniqueItems": true
        },
        "members": {
            "type": "array",
            "description": "The members of the team.",
            "items": {
                "$ref": "#/$defs/member"
            },
            "minItems": 4,
            "maxItems": 8,
            "uniqueItems": true
        },
        "products": {
            "type": "array",
            "description": "The products provided by this team.",
            "items": {
                "$ref": "#/$defs/product"
            }
        },
        "uniqueItems": true
    },
    "$defs": {
        "teamname_list": {
            "type": "string",
            "description": "The list of team names.",
            "enum": [
                "Platform",
                "CRM",
                "Product",
                "Conversions"
            ]
        },
        "external_customer_list": {
            "type": "string",
            "description": "The list of external customers",
            "enum": [
                "Website Customers",
                "Partners"
            ]
        },
        "customer_list": {
            "anyOf": [
                {
                    "$ref": "#/$defs/teamname_list"
                },
                {
                    "$ref": "#/$defs/external_customer_list"
                }
            ]
        },
        "overview": {
            "type": "object",
            "required": [
                "name",
                "mission",
                "current_work",
                "teams_working_with",
                "homepage",
                "backlog",
                "wiki",
                "calendar"
            ],
            "properties": {
                "name": {
                    "$ref": "#/$defs/teamname_list"
                },
                "mission": {
                    "type": "string",
                    "description": "The mission of the team."
                },
                "current_work": {
                    "type": "array",
                    "description": "What the team is currently working on.",
                    "items": {
                        "type": "string"
                    },
                    "uniqueItems": true
                },
                "teams_working_with": {
                    "type": "array",
                    "description": "The list of teams this team works with.",
                    "items": {
                        "name": {
                            "$ref": "#/$defs/teamname_list"
                        }
                    },
                    "uniqueItems": true
                },
                "homepage": {
                    "type": "string",
                    "description": "This is the hompage of the team including links, status and metrics.",
                    "pattern": "<a href='.*'>Homepage</a>"
                },
                "backlog": {
                    "type": "string",
                    "description": "The name and link to the backlog.",
                    "pattern": "<a href='.*'>Backlog</a>"
                },
                "wiki": {
                    "type": "string",
                    "description": "This is the wiki for the team.",
                    "pattern": "<a href='.*'>Wiki</a>"
                },
                "calendar": {
                    "type": "string",
                    "description": "The is the teams calendar",
                    "pattern": "<a href='.*'>Calendar</a>"
                }
            }
        },
        "member": {
            "type": "object",
            "required": [
                "name",
                "roles",
                "skills"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of team member"
                },
                "email": {
                    "type": "string",
                    "description": "Email address of team member",
                    "pattern": "^[^@]+@[^@]+\\.[^@]+$"
                },
                "roles": {
                    "type": "array",
                    "description": "Roles team member has",
                    "items": {
                        "type": "string",
                        "enum": [
                            "Product Owner",
                            "Scrum Master",
                            "Technical Lead",
                            "Engineer",
                            "Analyst"
                        ]
                    },
                    "uniqueItems": true
                },
                "skills": {
                    "type": "array",
                    "description": "Skills team member has",
                    "items": {
                        "type": "string",
                        "enum": [
                            "C#",
                            "SQL",
                            "Python",
                            "Data Science",
                            "Front End Development",
                            "Powershell",
                            "Terraform",
                            "Bicep"
                        ]
                    },
                    "uniqueItems": true
                }
            }
        },
        "communication": {
            "type": "object",
            "required": [
                "medium",
                "channels"
            ],
            "properties": {
                "medium": {
                    "type": "string",
                    "description": "Name of medium to comminicate through",
                    "enum": [
                        "Email",
                        "Slack",
                        "Teams"
                    ]
                },
                "channels": {
                    "type": "array",
                    "description": "Channels that can be communicated on through the medium",
                    "uniqueItems": true,
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "The name of the channel including link to communnicate with team",
                                "pattern": "<a href='.*'>.*</a>"
                            },
                            "description": {
                                "type": "string",
                                "description": "A description of the channels purpose"
                            }
                        }
                    }
                }
            }
        },
        "product": {
            "type": "object",
            "required": [
                "name",
                "purpose",
                "sla",
                "customers",
                "codebase"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of the product provided",
                    "enum": [
                        "Event Broker",
                        "Schema Registry"
                    ]
                },
                "purpose": {
                    "type": "string",
                    "description": "The purpose of this product"
                },
                "sla": {
                    "type": "string",
                    "description": "The service level agreement for this product"
                },
                "customers": {
                    "type": "array",
                    "description": "Customers that use this product",
                    "uniqueItems": true,
                    "items": {
                        "$ref": "#/$defs/customer_list"
                    }
                },
                "codebase": {
                    "type": "array",
                    "description": "Codebase that supports this service",
                    "uniqueItems": true,
                    "items": {
                        "type": "string",
                        "description": "The name of the codebase including link.",
                        "pattern": "<a href='.*'>.*</a>"
                    }
                }
            }
        }
    }
}

=== griff182uk/teamconfig/teams/crm_team.json
{
    "overview": {
        "name": "Platform",
        "mission": "Providing reliable shared infrastructure and repeatable deployment pipelines to improve value stream engineering throughput.",
        "current_work": [
            "Investigating suitable event broker technologies",
            "Creating common templates for storage containers"
        ],
        "teams_working_with": [
            "",
            "Conversions",
            "Product"
        ],
        "homepage": "<a href='https://github.com/griff182uk/teamconfig/blob/master/teamlinks/homepage.md'>Homepage</a>",
        "backlog": "<a href='https://github.com/griff182uk/teamconfig/issues?q=is%3Aopen+is%3Aissue+project%3Agriff182uk%2Fteamconfig%2F1'>Backlog</a>",
        "wiki": "<a href='https://github.com/griff182uk/teamconfig/wiki/example-platform-wiki'>Wiki</a>",
        "calendar": "<a href='https://github.com/griff182uk/teamconfig/blob/master/teamlinks/calendar.md'>Calendar</a>"
    },
    "communications": [
        {
            "medium": "Email",
            "channels": [
                {
                    "name": "<a href='https://github.com/griff182uk/teamconfig/blob/master/teamlinks/email.md'>platform-team@teamconfig.com</a>",
                    "description": "This is the channel for contacting the team for general discusssion"
                },
                {
                    "name": "<a href='https://github.com/griff182uk/teamconfig/blob/master/teamlinks/email.md'>platform-team-support@teamconfig.com</a>",
                    "description": "This is the channel for requesting assistance from the team"
                }
            ]
        },
        {
            "medium": "Slack",
            "channels": [
                {
                    "name": "<a href='https://example-teamconfig.slack.com/archives/C02RFF8BPQU'>platform-team</a>",
                    "description": "This is the channel for intra-team chat and scrums"
                },
                {
                    "name": "<a href='https://example-teamconfig.slack.com/archives/C02RRRQCM5F'>platform-support</a>",
                    "description": "This is the channel for anyone outside the team requiring support from this team"
                },
                {
                    "name": "<a href='https://example-teamconfig.slack.com/archives/C02RD6K7B34'>platform-status-dev</a>",
                    "description": "This is the channel for posting development deployments and any alerts"
                },
                {
                    "name": "<a href='https://example-teamconfig.slack.com/archives/C02S2V9JRQ8'>platform-status-live</a>",
                    "description": "This is the channel for posting production deployments, any alerts and for raising on-call issues manually"
                }
            ]
        }
    ],
    "members": [
        {
            "name": "Cartman",
            "email": "Cartman@teamconfig.com",
            "roles": [
                "Product Owner",
                "Analyst"
            ],
            "skills": [
                "Powershell",
                "SQL"
            ]
        },
        {
            "name": "Kyle",
            "email": "kyle@teamconfig.com",
            "roles": [
                "Scrum Master"
            ],
            "skills": [
                "Powershell"
            ]
        },
        {
            "name": "Stan",
            "email": "stan@teamconfig.com",
            "roles": [
                "Technical Lead",
                "Engineer"
            ],
            "skills": [
                "Powershell",
                "Terraform",
                "Bicep"
            ]
        },
        {
            "name": "Kenny",
            "email": "kenny@teamconfig.com",
            "roles": [
                "Engineer",
                "Scrum Master"
            ],
            "skills": [
                "Powershell",
                "Terraform",
                "Bicep"
            ]
        }
    ],
    "products": [
        {
            "name": "Event Broker",
            "purpose": "Provide a decoupled shared message broker and immutable log for all events of the business.",
            "sla": "99.99%",
            "customers": [
                "Conversions",
                "CRM",
                "Product"
            ],
            "codebase": [
                "<a href='https://github.com/griff182uk/teamconfig/blob/master/teamlinks/readme.md'>Event Broker</a>"
            ]
        },
        {
            "name": "Schema Registry",
            "purpose": "Provide a central schema repository for applications and services to deploy their schemas to.",
            "sla": "99.99%",
            "customers": [
                "Conversions",
                "CRM",
                "Product"
            ],
            "codebase": [
                "<a href='https://github.com/griff182uk/teamconfig/blob/master/teamlinks/readme.md'>Schema Registry</a>"
            ]
        }
    ]
}
